### ISSUE TITLE
[QUESTION] Mantis Neopixel Duct CAD

### ISSUE THREAD

**Issue by skyne** [Minsekt/moronvods#1]
Hi, sorry about opening an issue here, but i could not find any contact to you.

I'm curious if you can maybe share the original CAD files for the Mantis Neopixel Duct, I've used it with my Dragon hotend and loved it so much, however, now I'm migrating to Rapido, for which the duct's mounting tabs are in a different position, so i would like to adapt your mod to that version as well.

Thanks,
Skyne

**Comment by Minsekt** [comment]
hey, i should still have it somewhere. ill push it in a few minutes. 👍🏻

**Comment by skyne** [comment]
Hey, i appreciate the quick response, did you have a chance to find the file maybe? :)

**Comment by Minsekt** [comment]
sorry it got stuck pushing it seems. its uploaded now.
